<?php

namespace Database\Seeders;

use App\Core\Models\Menu;
use Illuminate\Database\Seeder;
use Spatie\Permission\Models\Role;

class ActionPermissionSeeder extends Seeder
{
    public function run(): void
    {
        // top-level menu name => [submenu name, friendly nav_name]
        // Each becomes a real, non-nav submenu — its permission name is
        // auto-generated by the Menu model (menu.<slug>), not hand-picked.
        $submenus = [
            'Menu Management'     => ['Menu Management Destroy', 'Delete'],
            'Roles & Permissions' => ['Roles & Permissions Destroy', 'Delete'],
            'Manage Users'        => ['Manage Users Destroy', 'Delete'],
            'Activity Logs'       => ['Activity Logs Clear', 'Clear'],
        ];

        $createdPermissionNames = [];

        foreach ($submenus as $parentName => [$submenuName, $navName]) {
            $parent = Menu::where('name', $parentName)->first();

            if (! $parent) {
                continue;
            }

            $order = ($parent->children()->max('order') ?? 0) + 1;

            $submenu = Menu::firstOrCreate(
                ['name' => $submenuName, 'parent_id' => $parent->id],
                ['nav_name' => $navName, 'is_nav' => false, 'order' => $order, 'is_active' => true]
            );

            $createdPermissionNames[] = $submenu->permission_name;
        }

        $admin = Role::where('name', 'Admin')->first();
        if ($admin) {
            $admin->givePermissionTo($createdPermissionNames);
        }
    }
}